backend:
  name: git-gateway
  branch: base

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Blog
    folder: content/blogs
    create: true
    slug: index
    path: "{{year}}/{{month}}/{{title}}/index"
    preview_path: "blog/{{fields.path}}"
    summary: "Version: {{version}} - {{title}}"
    sortable_fields: ["commit_date", "title", "commit_author", "language.en"]
    fields:
      - label: Path
        name: path
        default: /slug-id-or-name
        comment: "The URL path that this blog will be accessed on"

      - label: Date
        name: date
        widget: datetime

      - label: Post Type
        name: type
        widget: select
        options: ["announcement", "updates", "others"]
        default: announcement

      - label: Title
        name: title
        widget: string

      - label: Collection
        name: collection
        widget: hidden
        default: blog

      - label: Featured Image
        name: thumbnail
        widget: image
        choose_url: false

      - label: Body
        name: body
        widget: markdown
        pattern: [".{20,}", "Must have at least 20 characters"]

  - name: event
    label: Event
    folder: content/events
    create: true
    fields:
      - {
          name: path,
          label: Path,
          comment: "The URL path that this blog will be accessed on",
        }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
